### ISSUE TITLE
Eldar Craftworld bug report

### ISSUE THREAD

**Issue by thefbgnome** [BSData/wh40k-7th-edition#960]
First off great job thanx... a few bugs spotted in quick pass... 
1) in Aspect Host Formation Fire Dragons do not have the ability to take thier Dedicated Transport
2) Wraith Constructs do not have the ability to take Hemlock Flyer
3) Nightspinners are missing the Monofilament Shroud rule (the do have the Monofilament rule listed)

**Comment by thefbgnome** [comment]
Further review the Fire Dragons issue is also in CAD
the Hemlock issue... Hemlock is not even in the cat file...

**Comment by thefbgnome** [comment]
Fire dragon exarch is listed as 3+/4++ save...
when adding a guardian platform get an error listing that platform max is 0

**Comment by thefbgnome** [comment]
Striking Scorpions Exarch. Stalker should be inclusive in the Exarch, but is listed as a 0pt option upgrade. (Other Exarch appear to have their Exarch powers as inclusive).

**Comment by thefbgnome** [comment]
Twinlinked EML (waveserpent) is missing Starsworm profile (the flakk)

**Comment by thefbgnome** [comment]
Wraithknight scatter laser upgrade listed as 20 points when it should be 15

**Comment by Toreador13** [comment]
Thanks! 
v4 will have these fixes in. Hemlock was in list, but for some reason it was set to hidden. All other items should be fixed.

**Comment by thefbgnome** [comment]
Thanx found one more...If you try to add Additional Vaul Support Battery to a Guardian Host formation the weapon is both a D-Cannon and a Shadow Weaver, and when you try to deselect one it crashes. But good work getting something done so quickly.

**Comment by Toreador13** [comment]
That is an odd one, and it only happened if you selected a different weapon before choosing another platform. It had to do with the warlock leader being in that grouping. Fixed now.

**Comment by AnUnearthlyChilde** [comment]
Weapons platforms for guardians are causing a notification of having too many when only one is selected as part of the guardian battlehost.

Not sure if it applies to standard cad selected guardians or not, but possibly worth a look also.

**Comment by Paland49** [comment]
Wraithknight's heavy wraithcannons may be exchange for free. But it says in the cost "Ghostglaive and Scattershield 10 points" and Suncannon and "Scattershield 40 points"

**Comment by thefbgnome** [comment]
When you uncheck the exarch for the dire avenger shrine it incorrectly says you must have one in validation.

**Comment by thefbgnome** [comment]
Also all the old FW validation issues still remain (saying may only have one lynx and one revanent)

**Comment by Toreador13** [comment]
I won't be fixing any of the FW validation, as that would take me a bit to research and I don't have all the books.

Other issues have been fixed, but will have to be pushed after we find some more.

**Comment by thefbgnome** [comment]
Thanx ... the FW issue is actually tied to LOW... is only an issue in apoc if you try to take more than one of any LOW FW unit the validation says you can only take one as this is obviously wrong because you are able to take any units in any amount in apoc most just ignore validation when playing apoc anyway...

**Comment by thefbgnome** [comment]
I wish I had a computer to help here ... bug hunt is best I can do to help... thanx for being so responsive you guys do a great job.

**Comment by TailssTF** [comment]
Autarch's default pistol shold be shuriken, not fusion. Also, Star Lance (Melee) S+5, not S8.

**Comment by thefbgnome** [comment]
Ok version 4 seemed to have created the Autarch issue (I know it wasnt there in 3) also the twin linked EML on wave serpents lists the Starhawk seperate from the others and doesnt say they are twinlinked like the others do. The scorpion exarch issue is also still there. (It lists stalker as a zero pt upgrade when it is actually standard)

**Comment by Toreador13** [comment]
Yeah, looks like for some reason Fusion pistol was set to min 1 when I entered it. 
I don't see the scorpion exarch issue. In mine, in the two places the exarch is it is now a rule and doesn't show as a selection. Can you tell me which selection? There should be only two, one in the aspect host and one in the elite slot of a CAD. Fixed all the other issues you both found.

**Comment by thefbgnome** [comment]
Hmm your right the scorpion exarch issue is fixed... I check all reports I have collected ... must not have checked that one before passing it on... sorry... thanx for the great work.

**Comment by Toreador13** [comment]
Not a problem. You just had me worried I was missing something!

**Comment by thefbgnome** [comment]
Avatar of Khaine... I am not certain but it seems the one per army issue is lifted (cannot find anything that now says one per army anymore...) if so then validation issue if you take two or three (I guess as LOW in CAD is limited to one... but as command choice should be allowed 3 per core choice...)

**Comment by Anggul** [comment]
Wraithlords taking a scatter laser are paying 20pts when it should be 15pts

**Comment by Anggul** [comment]
Also death spinners are coming up as an option for Warp Spiders rather than just being a 'flat' selection, and the minimum is one, so it throws up an error when you take them.

**Comment by thefbgnome** [comment]
The deathspinner issue is only in CAD the aspect host it works fine

**Comment by Toreador13** [comment]
Ok, found all that, and v8 is in the works now.

**Comment by thefbgnome** [comment]
Warwalkers have the option to take holofields... they shouldnt have this option

**Comment by sigma100** [comment]
Amazing job, lightning fast work and with few errors! Thanks so much.  Anyways, I noticed a small issue with the wraithhost formation.
It is supposed to have 1 spiritseer, 3 wraithguard/blades, 1 wraithlord, and 1 wraithknight, but it is listed as having 0 spiritseers and 2 wraithlords.

Thanks again, your work is very much appreciated.

**Comment by thefbgnome** [comment]
Hmmm... unable to replicate what you said... the wraithost looks fine to me... perhaps you need to grab latest file?

**Comment by sigma100** [comment]
Ah, I see the problem now.  I was using the Ghost Warrior formation, not the Wraith Host.  Nevermind!

**Comment by Toreador13** [comment]
v8 contains all these fixes. Closing thread. Any new bugs submit new bug requests. Thanks everyone for making this a lot easier!
